server.name: kibana
server.host: "0"
elasticsearch.hosts: https://elasticsearch:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true
server.ssl.enabled: true
server.ssl.keystore.path: "/usr/share/kibana/config/certs/elastic-certificates.p12"
server.ssl.keystore.password: ${ELASTIC_CERT_PASSWORD}
server.ssl.truststore.path: "/usr/share/kibana/config/certs/elastic-certificates.p12"
server.ssl.truststore.password: ${ELASTIC_CERT_PASSWORD}

elasticsearch.username: elastic
elasticsearch.password: ${ELASTIC_PASSWORD}
elasticsearch.ssl.verificationMode: "none"