http.host : "0.0.0.0"

log.level: info
log.format: plain
path.logs: /usr/share/logstash/log

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
xpack.monitoring.elasticsearch.hosts: "https://elasticsearch:9200"
xpack.monitoring.elasticsearch.ssl.verification_mode: "certificate"
xpack.monitoring.elasticsearch.ssl.keystore.path : "/usr/share/logstash/config/certs/elastic-certificates.p12"
xpack.monitoring.elasticsearch.ssl.truststore.path : "/usr/share/logstash/config/certs/elastic-certificates.p12"
xpack.monitoring.elasticsearch.ssl.keystore.password: ${ELASTIC_CERT_PASSWORD}
xpack.monitoring.elasticsearch.ssl.truststore.password: ${ELASTIC_CERT_PASSWORD}