version: '3'

services:
  #backend framework
  django:
    build:
      context: ../srcs/backend
      dockerfile: ../../docker/django/dockerfile
    container_name: django
    restart: always
    expose:
      - "8000"
    networks:
      - ft_network
    env_file:
      .env
    depends_on:
      - postgresql
    tty: true
  
  #Database server
  postgresql:
    build: ./postgresql
    container_name: postgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - ft_network
    env_file:
      .env
    tty: true
  
  #webserver
  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - ft_network
    tty: true
    depends_on:
      - django
  
  #ELK containers
  # elasticsearch:
  #   build: ./ELK/elasticsearch
  #   tty: true

  # logstash:
  #   build: ./ELK/logstash
  #   tty: true

  # kibana:
  #   build: ./ELK/kibana
  #   tty: true


networks:
  ft_network:
    driver: bridge
