# Generated by Django 4.2.8 on 2024-02-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiRoomInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Roomid', models.CharField()),
                ('RoomName', models.CharField()),
                ('GameStatus', models.BooleanField(default=False)),
                ('QuantityPlayer', models.PositiveSmallIntegerField()),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('QuantityPlayerReady', models.PositiveSmallIntegerField()),
                ('client1', models.JSONField(null=True)),
                ('client2', models.JSONField(null=True)),
                ('client3', models.JSONField(null=True)),
                ('client4', models.JSONField(null=True)),
                ('paddle1', models.JSONField(null=True)),
                ('paddle2', models.JSONField(null=True)),
                ('paddle3', models.JSONField(null=True)),
                ('paddle4', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'room_info',
            },
        ),
    ]
