# Generated by Django 4.2.8 on 2024-02-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiRoomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roomid', models.CharField()),
                ('RoomName', models.CharField()),
                ('QuantityPlayer', models.PositiveSmallIntegerField()),
                ('CreatedTime', models.DateTimeField(auto_now_add=True)),
                ('client1', models.JSONField()),
                ('client2', models.JSONField()),
                ('client3', models.JSONField()),
                ('client4', models.JSONField()),
                ('paddle1', models.CharField()),
                ('paddle2', models.CharField()),
                ('paddle3', models.CharField()),
                ('paddle4', models.CharField()),
            ],
            options={
                'db_table': 'Room_info',
            },
        ),
    ]
