# Generated by Django 4.2.8 on 2024-02-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiGameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField()),
                ('ballx', models.PositiveSmallIntegerField()),
                ('bally', models.PositiveSmallIntegerField()),
                ('ballvx', models.PositiveSmallIntegerField()),
                ('ballvy', models.PositiveSmallIntegerField()),
                ('paddle1x', models.PositiveSmallIntegerField()),
                ('paddle1y', models.PositiveSmallIntegerField()),
                ('paddle2x', models.PositiveSmallIntegerField()),
                ('paddle2y', models.PositiveSmallIntegerField()),
                ('paddle3x', models.PositiveSmallIntegerField()),
                ('paddle3y', models.PositiveSmallIntegerField()),
                ('paddle4x', models.PositiveSmallIntegerField()),
                ('paddle4y', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'Game_info',
            },
        ),
        migrations.AlterModelTable(
            name='multiroominfo',
            table='Room_info',
        ),
    ]
