FROM nginx:1.25.3-alpine

WORKDIR /etc/nginx

RUN mkdir -p /etc/nginx/certs && \
	apk add --no-cache openssl && \
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/server.key -out /etc/nginx/certs/server.crt -subj /

# RUN apk add --no-cache nss-tools
# RUN wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64 -O /usr/local/bin/mkcert
# RUN chmod +x /usr/local/bin/mkcert

# RUN mkcert -install
# RUN mkdir -p /etc/nginx/certs
# RUN mkcert -key-file /etc/nginx/certs/server.key -cert-file /etc/nginx/certs/server.crt localhost 127.0.0.1 ::1

COPY config/nginx.conf /etc/nginx/nginx.conf

COPY . /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]