FROM nginx:1.25.3-alpine

WORKDIR /etc/nginx

RUN mkdir -p /etc/nginx/certs && \
	apk add --no-cache openssl && \
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/certs/server.key -out /etc/nginx/certs/server.crt -subj /

COPY config/nginx.conf /etc/nginx/nginx.conf

COPY . /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]