FROM python:3.9-slim

ENV PYTHONDONTWRITTEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir ./backend ./settings

COPY ./settings ./settings

RUN pip install --upgrade pip && pip install --no-cache-dir -r ./settings/requirements.txt && pip install -U channels["daphne"]

RUN chmod 777 ./settings/wait_for_it.sh

COPY . ./backend

WORKDIR /backend

CMD ["../settings/wait_for_it.sh", "localhost:5432", "--" ,"python3", "manage.py", "runserver", "0.0.0.0:8000"]
