FROM python:3.9-slim

COPY requirements.txt ./

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && mkdir ./backend

COPY . ./backend

EXPOSE 8000

WORKDIR ./backend

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]