FROM logstash:8.12.1

RUN logstash-plugin install logstash-filter-json

RUN logstash-plugin install logstash-output-elasticsearch

COPY config/logstash.yml /usr/share/logstash/config/logstash.yml

COPY config/pipeline.conf /usr/share/logstash/pipeline/pipeline.conf

RUN mkdir -p /usr/share/logstash/log/nginx

COPY ./certificat/elastic-certificates.p12 /usr/share/logstash/config/certs/elastic-certificates.p12