FROM logstash:7.17.16

RUN logstash-plugin install logstash-output-elasticsearch

COPY config/logstash.yml /usr/share/logstash/config/logstash.yml
COPY config/logstash.conf /usr/share/logstash/pipeline/logstash.conf